spring:
  application:
    name: snyk-employee-api
  jpa:
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
    show-sql: true
  h2:
    console:
      path: /h2-console
